### ISSUE TITLE
Mark status as in-progress rather than as failed

### ISSUE THREAD

**Issue by terrajobst** [gr2m/wip-bot#19]
We're using the bot in our organization. A contributor [raised](https://github.com/dotnet/coreclr/issues/14593) the issue that marking the status as failed might be too draconian. We've many builds across many operating system and each of those reports a status. When a PR is marked as "not ready" (i.e. with a red X) folks are alarmed trying to find a build break. For these scenarios it seems better if the PR status could be set to yellow, i.e. in-progress.

Could this be a configuration setting?

**Comment by gr2m** [comment]
🤔 

There is currently no configuration for the WIP bot and I’d like to keep it that way, it’s the most simple GitHub App I know and I use it a lot as an example or template for other apps. 

You could easily deploy your own, I’ve made a simple deploy-to-glitch app: https://probot.glitch.me. After the deploy you can just make the change in the code :)

But I do wonder if "pending" isn’t a better value for a pull request that is still in progress, instead of setting it to error. It’d still block a PR if the WIP status is enforced via branch protection, right?

---

PS: just a heads up that the WIP bot is currently down due to a big outage at Zeit: https://zeit-status.co/

**Comment by terrajobst** [comment]
Awesome. Thanks for fixing this so fast. Just noticed the change on our side. Looks great!

**Comment by gr2m** [comment]
thanks for bringing it up, I like it better myself, too 👍
