### ISSUE TITLE
Feature request: allow the bot to set a tag when a PR is WIP

### ISSUE THREAD

**Issue by TravisEz13** [gr2m/wip-bot#54]
The tag name should be configurable.  Perhaps via a YML file?

**Comment by gr2m** [comment]
Hi @TravisEz13, that sounds like a good idea, I’m sure it would be useful to more projects out there. For wip-bot it is out of scope, but it’s fairly simple to create your own app. wip-bot is used frequently as template for other bots due to its simplicity.

I’ll close the issue but if you have any questions about how to build your own bot, comment below or even better, join the Probot community: https://probot.github.io/community/

**Comment by gr2m** [comment]
One additional consideration: it would require the bot to have write [access to pull requests](https://developer.github.com/v3/apps/permissions/#permission-on-pull-requests), which might be a problem for people to install the app. Unfortunately permissions are not granular enough to only allow adding/removing labels.
